# Generated by Django 5.1.6 on 2025-03-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
