# Generated by Django 4.2.19 on 2025-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_creator_storetable_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='storetable',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
