# Generated by Django 4.2.19 on 2025-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_name_alter_storetable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetable',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
